# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vbox, override|
    vbox.cpus = 2
    vbox.memory = 1024
    vbox.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.provider "libvirt" do |libvirt, override|
    libvirt.cpus = 2
    libvirt.memory = 1024
    libvirt.driver = 'kvm'
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo hostname openshift.example.com
     sudo yum -y update
     sudo cp sync/*.repo /etc/yum.repos.d/
     sudo yum -y install docker openshift-node openshift-master
     sudo openshift start --write-config=/etc/openshift --hostname=openshift.example.com
     sudo sed -i 's/master.yaml/master-config.yaml/' /etc/sysconfig/openshift-master
     sudo mv /etc/openshift/node-openshift.example.com/* /etc/openshift/node/
     sudo rmdir  /etc/openshift/node-openshift.example.com
     sudo systemctl enable docker openshift-master openshift-node
     sudo systemctl start openshift-master openshift-node
     sudo mkdir /root/.kube /home/vagrant/.kube
     sudo cp /etc/openshift/master/admin.kubeconfig /home/vagrant/.kube/config
     sudo cp /etc/openshift/master/admin.kubeconfig /root/.kube/config
     sudo chown -R vagrant:vagrant /home/vagrant/.kube
     sudo oadm registry --credentials=/etc/openshift/master/openshift-registry.kubeconfig
     echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' | oc create -f -
     oc get scc privileged -o yaml > /tmp/privileged.tmp
     echo "- system:serviceaccount:default:router" >> /tmp/privileged.tmp
     oc replace scc privileged -f /tmp/privileged.tmp
     CA=/etc/openshift/master
     oadm ca create-server-cert --signer-cert=$CA/ca.crt --signer-key=$CA/ca.key --signer-serial=$CA/ca.serial.txt --hostnames='*.cloudapps.example.com' --cert=cloudapps.crt --key=cloudapps.key
     cat cloudapps.crt cloudapps.key $CA/ca.crt > cloudapps.router.pem
     oadm router --default-cert=cloudapps.router.pem --credentials=/etc/openshift/master/openshift-registry.kubeconfig --service-account=router
  SHELL
end
